### ISSUE TITLE
Swift support

### ISSUE THREAD

**Issue by wirakoon78** [Microsoft/Cognitive-Face-iOS#7]
I am building an app using Swift3.0 , I noticed this sdk supports ObjectiveC only. 
Can you release new version of SDK for Swift? 

Please let me know,
Thanks

**Comment by wangjun-microsoft** [comment]
Thank you for using Face service, since Swift support Cocoa and ObjectiveC, we currently only release this ObjectiveC version SDK. But we'll take Swift version SDK as a candidate task to our team.

For more information about using Cocoa in Swift, hope [this site ](https://developer.apple.com/library/prerelease/content/documentation/Swift/Conceptual/BuildingCocoaApps/) could help.

Thanks

**Comment by huxuan** [comment]
Close as no further update from reporter.
